
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package mx.unam.aragon.interprete.sintactico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FINLLAVE = 14;
  public static final int IGUAL = 16;
  public static final int CIR = 4;
  public static final int LIN = 6;
  public static final int MAYORQUE = 19;
  public static final int MV = 10;
  public static final int ID = 23;
  public static final int REC = 5;
  public static final int PS = 3;
  public static final int OB = 11;
  public static final int F = 8;
  public static final int COMA = 15;
  public static final int LPR = 2;
  public static final int EOF = 0;
  public static final int C = 7;
  public static final int MENORQUE = 20;
  public static final int PAR_IZQ = 18;
  public static final int error = 1;
  public static final int PAR_DER = 17;
  public static final int PUNTOCOMA = 12;
  public static final int ENTERO = 22;
  public static final int MIENTRAS = 9;
  public static final int MAS = 21;
  public static final int LLAVE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPR",
  "PS",
  "CIR",
  "REC",
  "LIN",
  "C",
  "F",
  "MIENTRAS",
  "MV",
  "OB",
  "PUNTOCOMA",
  "LLAVE",
  "FINLLAVE",
  "COMA",
  "IGUAL",
  "PAR_DER",
  "PAR_IZQ",
  "MAYORQUE",
  "MENORQUE",
  "MAS",
  "ENTERO",
  "ID"
  };
}

